apiVersion: apps/v1
kind: Deployment
metadata: 
  name: adontsov-main-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: adontsov-shift-src
  template:
    metadata:
      name: adontsov-pod
      labels:
        app: adontsov-shift-src
    spec:
      containers:
        - name: adontosov-container
          image: registry.gitlab.com/shift-python/y2023/homeworks/doncov-a/week8-task1/src:latest
          ports:
            - containerPort: 24104
          resources:
            limits:
              cpu: 200m
              memory: "400Mi"
          readinessProbe:
            httpGet:
              path: /ready
              port: 24104
            failureThreshold: 2
            initialDelaySeconds: 10
            periodSeconds: 3
            successThreshold: 2
          livenessProbe:
            httpGet:
              path: /live
              port: 24104
            failureThreshold: 2
            initialDelaySeconds: 15
            periodSeconds: 1
            successThreshold: 1
          env:
            - name: HOST
              valueFrom:
                configMapKeyRef:
                  key: host
                  name: adontsov-configmap-src
            - name: PORT_SRC
              valueFrom:
                configMapKeyRef:
                  key: portsrc
                  name: adontsov-configmap-src
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  key: db_username
                  name: adontsov-secret-src
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: db_password
                  name: adontsov-secret-src
            - name: POSTGRES_HOST
              valueFrom:
                secretKeyRef:
                  key: db_host
                  name: adontsov-secret-src
            - name: POSTGRES_PORT
              valueFrom:
                secretKeyRef:
                  key: db_port
                  name: adontsov-secret-src
            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  key: db_name
                  name: adontsov-secret-src

            
